@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
hehe -> Alice: 尼玛的
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml